# scene
scene: igibson
scene_id: Benevolence_1_int
build_graph: true
load_texture: true
pybullet_load_texture: true
trav_map_type: no_obj
trav_map_resolution: 0.1
trav_map_erosion: 3
should_open_all_doors: true
load_object_categories: [
  # window,
  # door,
  # shelf,
  # table,
  # chair,
  # console_table,
  # floor_lamp,
  # counter,
  # top_cabinet,
  # bottom_cabinet_no_top,
  ### 
  # chest,
  # sofa,
  # stool,
  # fridge,
  # microwave,
  # dishwasher,
  # oven,
  # sink,
  # carpet,
  # picture,
  # wall_mounted_tv,
]

# domain randomization
texture_randomization_freq: null
object_randomization_freq: null

# robot
robot: Quadrotor
is_discrete: false
velocity: 2
auto_navigation: true
use_custom_model: false
action_timestep: 10

# task
task: room_exploration
random_pos: true
# initial_pos: [[-0.4, 0.7, 0.1]]

# global map
gmap_format: voxel      # global map format: voxel / pc
down_sample_rate: 16    # down-sample rate to store the map
n_max_points: 50000     # maximum points in global map point cloud
duplicate_eps: 0.01     # duplicate threshold when merge local map into global
bounding_box: [[-5, 5], [-5, 5], [0, 3]]  # range of x,y,z
voxel_grid_size: [50, 50, 15]             # size of the global voxel grid
voxel_inside_points: 35                   # maximum points in a single voxel
n_max_voxels: 5000      # maximum occupied voxels in global voxel grid

# global grid & local grid
global_grid:
  grid_resolution: 0.2  # must be equal to resolution of global mapper
  grid_size: [80, 80, 20]  # centered at origin, elements must be even

# reward
collision_reward_weight: -0.5
map_explore_reward_scale: 4.0

# discount factor
discount_factor: 0.99

# termination condition
max_step: 100
max_collisions_allowed: 100

# misc config
initial_pos_z_offset: 0.1
collision_ignore_link_a_ids: [0, 1, 2]  # ignore collisions with these robot links

# sensor spec
output: [pos, gmap_voxel]  # gmap_pc or gmap_voxel
sensor_obs: [rgb, depth, pc]
# image
# Primesense Carmine 1.09 short-range RGBD sensor
# http://xtionprolive.com/primesense-carmine-1.09
fisheye: false
image_width: 128    # height of input rgbd image
image_height: 128   # width of input rgbd image
vertical_fov: 90
# depth
depth_low: 0.35
depth_high: 3.0
# scan
# SICK TIM571 scanning range finder
# https://docs.fetchrobotics.com/robot_hardware.html
# n_horizontal_rays is originally 661, sub-sampled 1/3
n_horizontal_rays: 220
n_vertical_beams: 1
laser_linear_range: 25.0
laser_angular_range: 220.0
min_laser_dist: 0.05
laser_link_name: laser_link

# sensor noise
depth_noise_rate: 0.0
scan_noise_rate: 0.0
